# Generated by Django 2.0.6 on 2018-06-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is task completed?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Task created at')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Task completed at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
